### ISSUE TITLE
Create vehicle motion model

### ISSUE THREAD

**Issue by ragingonyx** [gt-marine-robotics-group/Virtuoso#2]
We need to create a **mathematical representation** of our vehicle dynamics. Currently we have an empirical model, aka our physical vehicles, but this isn't ideal for tuning and testing in simulation. I hope to be able to leverage the empirical model in the creation of the theoretical model in a system like this.

![image](https://user-images.githubusercontent.com/42755385/135146662-869c0c34-52fc-499e-b226-0715016b4647.png)

Here's a useful link to get started with: [Video explaining how to make models.](https://www.youtube.com/watch?v=qhIjIu-Zk10&t=3s)

**Comment by ychitale** [comment]
Got it, thanks! I guess we might have to see if we can tune the model so that it matches the real-world behavior better.

**Comment by ychitale** [comment]
Building a simplified model based on Fossen's equations of motion (3DOF) as stated in: 
R. Rameshbabu, M. Steffens and D. Mavris, "System Identification Using the Modeling through Iterative Smoothing Algorithm," Global Oceans 2020: Singapore – U.S. Gulf Coast, 2020, pp. 1-7, doi: 10.1109/IEEECONF38699.2020.9389220.

![fossen_eqns_3dof](https://user-images.githubusercontent.com/80857485/140083242-8d3565e7-e365-4fc6-9eec-8fe7dc42d386.png)

Initially using values from VRX for hydrodynamic coefficients and mass properties
