### ISSUE TITLE
Create processing nodes for raw sensor data

### ISSUE THREAD

**Issue by ragingonyx** [gt-marine-robotics-group/Virtuoso#3]
We need to create a way to **process** our raw sensor data from the vehicles. This will be done through the perception pipeline package.  We should start developing **processing nodes** for each of sensors. 

The main sensors that we should focus on to process will be the **lidar** and **camera**. The way we will process these is as follows.

**Lidar** -> Point cloud data -> Ground Filter (optional) -> Downsample (voxel)
**Camera** -> Image data -> Grayscale -> Downsample (resolution shrink) 

There could be more processing done in the future, but for the first iteration, these should be sufficient. Each processing step should be it's own method within the node and the callback should call the processing functions in succession.

Here are some useful links for **Lidar Processing**:
[STVL](https://navigation.ros.org/tutorials/docs/navigation2_with_stvl.html ) (Spatio Temporal Voxel Layer) 
[Ground Filter](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/perception/filters/ray_ground_classifier/design/ray-ground-classifier-design.md)

Here are a useful link for **Camera Processing**:
[Skimage](https://scikit-image.org/docs/stable/index.html)

**Comment by shrey-shivaiah** [comment]
Hello Eric,

Can I sign the waiver for the upcoming competition, I accidentally missed
it.

Thanks,
Shrey

**Comment by mroglan** [comment]
From last week:
Got AutowareAuto installed and the ray_ground_classifier_nodes running on a launch file. Also installed gazebo and working on finding out why the textures aren't rendering.

**Comment by mroglan** [comment]
Added downsampling for lidar point cloud data with voxel_grid_nodes from AutowareAuto. Used rosbags to test the lidar pipline.

**Comment by mroglan** [comment]
Created a Node for grayscaling image data and tested with a rosbag. Also painfully figured out how to resize hard disk for vm; will document how later.
