### ISSUE TITLE
Implementing YOLO

### ISSUE THREAD

**Issue by ragingonyx** [gt-marine-robotics-group/Virtuoso#5]
The other part of our obstacle avoidance server is object detection using image data. This should be done with YOLO due to it's ability to be run in real time. 

Like with Euclidean Clustering, I would like this to be done with a pre existing library. There are many tutorials out there on YOLO but the hard part is tuning it for our needs and hardware. We would most likely need to use Tiny-YOLO as a base model rather than base YOLO due to hardware requirements so keep this in mind as you're implementing this feature. The goal is to balance model size and complexity vs precision.

Useful Links:
[ROS2 implementation](https://github.com/ros2/openrobotics_darknet_ros)
[Another ROS2 implementation](https://github.com/Ar-Ray-code/darknet_ros_fp16)

**Comment by aapatni** [comment]
Relevant considering we use the Jetson TX2: https://github.com/dkarunakaran/ROS-node-YOLO-v3-tiny
